apiKeySecretRef: "test"
apiURL: "test"
provider: "eks"
namespace: "default"
createNamespace: false
additionalEnv:
  EKS_ACCOUNT_ID: test
  EKS_REGION: test
  EKS_CLUSTER_NAME: test
additionalSecretEnv:
  AWS_ACCESS_KEY_ID: "key"
  AWS_SECRET_ACCESS_KEY: "secret"
clusterVPA:
  enabled: true
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 256Mi
isTest: true
