checks:
  exclude:
    - "unset-cpu-requirements"
    - "unset-memory-requirements"

  ignorePaths:
    - ./charts/egressd/**
    - ./charts/kvisor/**
    - ./charts/kvisord/**
    - ./charts/gpu-metrics-exporter/**
    - ./charts/castai-workload-autoscaler/**
    - ./charts/castai-workload-autoscaler-exporter/**
