apiVersion: v2
name: castai-pod-pinner
description: CAST AI Pod Pinning deployment chart.
type: application
version: 1.8.0
appVersion: "v1.9.2"
dependencies:
  - name: castai-pod-pinner-ext
    version: 1.1.0
    repository: file://child-charts/castai-pod-pinner-ext
    condition: castai-pod-pinner-ext.enabled
