# -- Token to be used for authorizing access to the CAST AI API.
apiKey: ""
image:
  repository: us-docker.pkg.dev/castai-hub/library/db-agent
  pullPolicy: IfNotPresent
  tag: ""  # uses values from _versions.tpl for default value
logLevel: info
organizationID: ""
cacheGroupID: ""
database:
  host: ""
  port: 5432
  # -- Username for database authentication
  username: ""
  # -- Password for database authentication
  password: ""
  # -- Name of secret with username for database authentication
  credentialsSecretRef: ""
# -- URL to the CAST AI API gRPC endpoint.
gRPCEndpoint: ""
collectors:
  indexes:
    # -- Frequency in which existing indexes are collected
    runsEvery: 15m
  metadata:
    # -- Frequency in which table metadata is collected
    runsEvery: 15m
  queries:
    # -- Frequency in which query statistics are collected
    runsEvery: 15m
  # -- Comma-separated list of schemas to exclude from collection (optional)
  excludedSchemas: ""
  # -- Comma-separated list of databases to exclude from database auto-discovery (optional)
  excludedDatabases: ""
