replicas: 1

# apiURL -- URL to the CAST AI API server.
apiURL: "api.cast.ai"

# apiKey -- Token to be used for authorizing access to the CAST AI API.
#
apiKey: ""

# cacheGroupID -- ID of the cache group for which cache configuration should be pulled.
#
cacheGroupID: ""

resources:
  proxy:
    cpu: "500m"
    # defines how much of proxy container disk space is allocated for cache.
    ephemeralStorage: 10Gi
    memory: "120Mi"
    # max allowed database size in disk
    cacheDbSizeBytes: 10000000000
    # maximum number of entries to keep in the proxy.
    maxCacheEntries: 1000000000
  queryProcessor:
    cpu: "500m"
    memory: "500Mi"

proxy:
  logLevel: "filter:info"

queryProcessor:
  logLevel: "warn"


# queryProcessorVersion overrides image version for query-processor, default used otherwise
queryProcessorVersion: ""

# proxyVersion overrides image version for proxy, default used otherwise
proxyVersion: ""
