# global -- Global values inherited from parent chart.
global:
  # global.commonLabels -- Labels to add to all resources (inherited from parent chart).
  commonLabels: {}
  # global.commonAnnotations -- Annotations to add to all resources (inherited from parent chart).
  commonAnnotations: {}

# commonLabels -- Labels to add to all resources (in addition to global.commonLabels).
commonLabels: {}

# commonAnnotations -- Annotations to add to all resources (in addition to global.commonAnnotations).
commonAnnotations: {}

nameOverride: ""
fullnameOverride: castai-cluster-controller-ext

# This chart is meant to provide possibility for granting permissions mostly. Permissions are granted by creating
# new role bindings to the SA created in the parent Chart. This SA name is used for creating role bindings.
serviceAccount:
  name: "castai-cluster-controller"
  # Specifies whether a service account and Clusteroles/Rolebindings should be created by helm chart or managed by User
  create: true
