# Default values for castai-azure-spot-handler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "castai-agent"

image:
  repository: castai/azure-spot-handler
  # Tag is set using Chart.yaml appVersion field.
  tag: ""
  pullPolicy: IfNotPresent

# URL to the API server
apiURL: ""

clusterID: ""
podAnnotations: {}
additionalEnv:
  PPROF_PORT: "6060"
  LOG_LEVEL: "5"

resources: {}

serviceAccount:
  # Annotations to add to the service account.
  annotations: {}

nodeSelector:
  key: scheduling.cast.ai/spot
  value: true
