{{- if and .Values.pgdog .Values.pgdog.enabled .Values.pgdog.user .Values.pgdog.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-pgdog-users
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
type: Opaque
stringData:
  users.toml: |
    [[users]]
    name = {{ .Values.pgdog.user | quote }}
    password = {{ .Values.pgdog.password | quote }}
{{- end }}
