apiVersion: v1
kind: ConfigMap
metadata:
  name: castai-sec-agent
  labels:
    {{- include "castai-sec-agent.labels" . | nindent 4 }}
data:
  {{- if .Values.apiURL }}
  API_URL: {{ required "apiURL must be provided" .Values.apiURL | quote }}
  {{- else }}
  API_URL: {{ required "castai.apiURL must be provided" .Values.castai.apiURL | quote }}
  {{- end }}
  FEATURES_KUBELINTER_ENABLED: {{ .Values.features.kubelinter.enabled }}
  FEATURES_KUBEBENCH_ENABLED: {{ .Values.features.kubebench.enabled }}
  FEATURES_IMAGE_SCAN_ENABLED: {{ .Values.features.imagescan.enabled }}
