apiVersion: v1
kind: ConfigMap
metadata:
  name: castai-sec-agent
  labels:
    {{- include "castai-sec-agent.labels" . | nindent 4 }}
data:
  API_URL: {{ required "castai.apiURL must be provided" .Values.castai.apiURL | quote }}
  CLUSTER_ID: {{ required "castai.clusterID must be provided" .Values.castai.clusterID | quote }}
  FEATURES_KUBELINTER_ENABLED: {{ .Values.features.kubelinter.enabled | quote }}
  FEATURES_KUBEBENCH_ENABLED: {{ .Values.features.kubebench.enabled | quote }}
  {{- if .Values.features.imagescan.enabled }}
  FEATURES_IMAGE_SCAN_ENABLED: "true"
  FEATURES_IMAGE_SCAN_IMAGE_COLLECTOR_IMAGE: "{{ .Values.features.imagescan.image.repository }}:{{ .Values.features.imagescan.image.tag | default .Chart.AppVersion }}"
  {{- end }}
