global:
  castai:
    apiKey: "test"
    apiURL: "http://mock-api.default.svc.cluster.local"
    provider: "eks"

kent:
  enabled: true
  agent:
    apiURL: "http://mock-api.default.svc.cluster.local"
    additionalEnv:
      EKS_ACCOUNT_ID: test
      EKS_REGION: test
      EKS_CLUSTER_NAME: test
  cluster-controller:
    castai:
      apiURL: "http://mock-api.default.svc.cluster.local"
  kentroller:
    castai:
      apiURL: "http://mock-api.default.svc.cluster.local"
  workload-autoscaler:
    castai:
      apiURL: "http://mock-api.default.svc.cluster.local"
  pod-mutator:
    castai:
      apiURL: "http://mock-api.default.svc.cluster.local"
  evictor:
    overrideEnvFrom: true
    envFrom:
      - secretRef:
          name: castai-credentials
      - configMapRef:
          name: castai-agent-metadata
  live:
    castai:
      apiURL: "http://mock-api.default.svc.cluster.local"
    controller:
      replicaCount: 0
    daemon:
      labelNodeSubnet: false
  metrics-server:
    enabled: false
