{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
  {{- include "omni-agent.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "omni-agent.annotations" . | nindent 4 }}
  {{- end }}
{{- end }}
