{{- if .Values.global.castai.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "castai-umbrella.credentialsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  API_KEY: {{ .Values.global.castai.apiKey | b64enc | quote }}
{{- end }}
