apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "workload-autoscaler.webhookName" . }}
  labels:
  {{- include "workload-autoscaler.labels" . | nindent 4 }}
  {{ if .Values.commonAnnotations -}}
  annotations:
    {{- include "workload-autoscaler.annotations" . | nindent 4 }}
  {{- end }}
webhooks:
  - name: workload-autoscaler.cast.ai
    failurePolicy: {{ .Values.webhook.failurePolicy | default "Ignore"}}
    sideEffects: None
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds | default 10 }}
    reinvocationPolicy: {{ .Values.webhook.reinvocationPolicy | default "Never"}}
    objectSelector:
      matchExpressions:
        # Exclude self.
        {{- include "workload-autoscaler.exludeSelfLabelSelectors" . | nindent 8 }}
        - key: workload-autoscaler.cast.ai/ignore
          operator: NotIn
          values:
            - "true"
        {{- if .Values.workloadWhitelistingEnabled }}
        - key: workload-autoscaler.cast.ai/enabled
          operator: In
          values:
            - 'true'
        {{- end }}
    namespaceSelector:
      matchExpressions:
        - key: workload-autoscaler.cast.ai/ignore
          operator: NotIn
          values:
            - "true"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    admissionReviewVersions:
      - v1
    clientConfig:
      {{- if .Values.webhook.url }}
      url: "{{ .Values.webhook.url }}/v1/mutate"
      {{- else }}
      service:
        name: {{ include "workload-autoscaler.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /v1/mutate
  {{- end }}
  - name: hpa-ownership.cast.ai
    failurePolicy: {{ .Values.webhook.failurePolicy | default "Ignore"}}
    sideEffects: None
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds | default 10 }}
    reinvocationPolicy: {{ .Values.webhook.reinvocationPolicy | default "Never"}}
    namespaceSelector:
      matchExpressions:
        - key: workload-autoscaler.cast.ai/ignore
          operator: NotIn
          values:
            - "true"
    rules:
      - apiGroups: ["autoscaling"]
        apiVersions: ["v2", "v2beta2"]
        operations: ["UPDATE", "DELETE"]
        resources: ["horizontalpodautoscalers"]
        scope: "Namespaced"
    admissionReviewVersions:
      - v1
    clientConfig:
      {{- if .Values.webhook.url }}
      url: "{{ .Values.webhook.url }}/v1/mutate-hpa"
      {{- else }}
      service:
        name: {{ include "workload-autoscaler.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /v1/mutate-hpa
  {{- end }}

