{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "workload-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workload-autoscaler.labels" . | nindent 4 }}
  {{ if .Values.commonAnnotations -}}
  annotations:
    {{- include "workload-autoscaler.annotations" . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "workload-autoscaler.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "workload-autoscaler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
