{{- if .Values.trustedCACert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workload-autoscaler.fullname" . }}-tls-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workload-autoscaler.labels" . | nindent 4 }}
  {{ if .Values.commonAnnotations -}}
  annotations:
    {{- include "workload-autoscaler.annotations" . | nindent 4 }}
  {{- end }}
data:
  TLS_CA_CERT: {{ .Values.trustedCACert | b64enc | quote }}
{{- end }}