apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.180
appVersion: f30e34fe5c5c0acddcba7bfc22da95bec156686a
annotations:
  release-date: "2025-11-10T09:06:38"
