apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.219
appVersion: 7ad3d2460a497567d115e33298ce0077ebb2f04f
annotations:
  release-date: "2025-12-08T12:14:05"
