apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.231
appVersion: e2f8f4b9d6c1d1f9bbdc6f92a56d74da952e7956
annotations:
  release-date: "2025-12-16T13:23:37"
