apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.245
appVersion: 5a463dd00da2ea1b544b32a1e43db942711caeeb
annotations:
  release-date: "2025-12-23T18:15:57"
