apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.163
appVersion: 8a37d739f3407a71916d5bd2622d1c33c7fda199
annotations:
  release-date: "2025-11-03T13:56:06"
