apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.302
appVersion: 876180c2bbd6a464c4a0e1c3b448a39ade7d2170
annotations:
  release-date: "2026-02-10T10:19:57"
