apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.297
appVersion: b14b1e1624d75fc06993f3b0d44262795587dec9
annotations:
  release-date: "2026-02-05T16:22:12"
