apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.159
appVersion: 9a5ef8e63f4e7424c60964432b28949b66cbf92f
annotations:
  release-date: "2025-11-03T10:43:03"
