apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.192
appVersion: 83e539b5b1a9644372fb30a5c72d364e900a89a3
annotations:
  release-date: "2025-11-21T10:24:35"
