apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.218
appVersion: df9859fe2a9c9069ca00436e891fdbce5469cbf7
annotations:
  release-date: "2025-12-05T15:06:40"
