apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.201
appVersion: a2c9c84b8b8d019073729e774648c76c46dffe0d
annotations:
  release-date: "2025-11-25T12:30:23"
