apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.323
appVersion: 1759cbedf79bdc1ea994b5840ac377ebe720e864
annotations:
  release-date: "2026-02-20T14:31:44"
