apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.270
appVersion: 20628ce4703208d10bb1ccbf529aa3590cd9f46f
annotations:
  release-date: "2026-01-19T19:37:42"
