apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.204
appVersion: a8437f0feb2b137b0e23fa32cd49d1122732a9a0
annotations:
  release-date: "2025-11-26T09:28:45"
