apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.305
appVersion: 40360725341a0ee417607023cde1ffe4c946ad8c
annotations:
  release-date: "2026-02-11T19:00:48"
