apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.249
appVersion: 4f90e2ee57c8b49e484cfbb34256db1c3ab39ae0
annotations:
  release-date: "2026-01-05T08:08:18"
