apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.171
appVersion: ac0bca398c84b67be635efbf5824168df03fdff1
annotations:
  release-date: "2025-11-06T11:40:04"
