apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.209
appVersion: 4b648108a78fc3428554ba2b6b0f1d8a11efacca
annotations:
  release-date: "2025-11-28T13:42:37"
