apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.232
appVersion: 2666c07f270f49436a090659d3b065cf9fdab8c3
annotations:
  release-date: "2025-12-17T09:01:53"
