apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.283
appVersion: cdb17d081f8435d6d139a2fb1b316306145b2a2c
annotations:
  release-date: "2026-01-27T11:18:03"
