apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.239
appVersion: 91bf14673384fe667e48ca95f5e580b6b0b90718
annotations:
  release-date: "2025-12-19T10:02:07"
