apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.279
appVersion: 5b9e50f9ab164f8816f6d58b6f8fdacd6f77d485
annotations:
  release-date: "2026-01-23T11:35:56"
