apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.275
appVersion: 53fd7c0015e5da7fb524a689ad8df6c3bac6675a
annotations:
  release-date: "2026-01-21T15:20:58"
