apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.296
appVersion: f30228a7a88df8b644f332140fdc5412d6707ce5
annotations:
  release-date: "2026-02-05T14:44:42"
