apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.278
appVersion: 20d6f6f32347ef3b0085b4059775a79ab8df1e2e
annotations:
  release-date: "2026-01-23T11:12:45"
