apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.197
appVersion: fdd0b0493dfb619cf42b87a58b43ab2758448f10
annotations:
  release-date: "2025-11-24T12:40:45"
