apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.328
appVersion: 2a60f09406c5696f9d36531e508bbe07aab61c8e
annotations:
  release-date: "2026-02-26T15:10:43"
