apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.315
appVersion: 666fc5d4a81cdf87a459a38b28c814d3b217433d
annotations:
  release-date: "2026-02-17T12:40:00"
