apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.236
appVersion: 58bade0673c5fb85ea4a641f4b425df830bf1c08
annotations:
  release-date: "2025-12-18T04:49:21"
