apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.165
appVersion: 6ba11a2851081bedf8646fdfc38c99eab93dc33e
annotations:
  release-date: "2025-11-04T10:19:50"
