apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.237
appVersion: c4f53df5294d0f72a3ffdee569d9631a19947362
annotations:
  release-date: "2025-12-18T13:55:20"
