apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.261
appVersion: 2ebdd2a624c698b3648729ec8bdc8be70889a314
annotations:
  release-date: "2026-01-13T08:39:08"
