apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.286
appVersion: 894a39e0fb6a28161f7d5b4f8e6271f668c34cf3
annotations:
  release-date: "2026-01-28T13:29:32"
