apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.280
appVersion: 916456e798dff5f01be826421a8874ab521ca70a
annotations:
  release-date: "2026-01-23T17:46:10"
