apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.318
appVersion: 1d4349b53cd9f20d6fa0bd69f53fa32c759103e3
annotations:
  release-date: "2026-02-18T14:14:32"
