apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.223
appVersion: 08adba833927da5987af5aa610b2ce3e3258ac20
annotations:
  release-date: "2025-12-10T13:16:35"
