apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.251
appVersion: 623345875fce8340eebddeff657543d827a3ac06
annotations:
  release-date: "2026-01-06T15:58:41"
