apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.301
appVersion: 37d99bf05685b0943cb81b38d1aa9fdc038f2fe1
annotations:
  release-date: "2026-02-10T09:39:30"
