apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.287
appVersion: e07cf941c26a013020a4febcf6f1dee43aaa448a
annotations:
  release-date: "2026-01-29T13:43:59"
