apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.277
appVersion: 51a9c18db6b1c6a0669a909288ab8d0e74573b06
annotations:
  release-date: "2026-01-23T10:03:36"
