apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.294
appVersion: e2e5de95d6662e95a01680c721a8f76655d70f51
annotations:
  release-date: "2026-02-03T08:34:40"
