apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.254
appVersion: 2a6e5fe085e914f312717c7617d787b8c2669bdb
annotations:
  release-date: "2026-01-07T17:49:47"
