apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.235
appVersion: eea1878f0a3df967149e20ac17ee5f30ae5c074e
annotations:
  release-date: "2025-12-17T15:57:21"
