apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.166
appVersion: e0396ac748162c92b198f8d27918d9215f9ec88a
annotations:
  release-date: "2025-11-04T13:27:15"
