apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.164
appVersion: b44cdec76bbabd5f1a2c5e3fa3cd7c99295f862d
annotations:
  release-date: "2025-11-04T08:41:29"
