apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.273
appVersion: bd3161a53b42406bfd577416bf2c0a0d04a5217a
annotations:
  release-date: "2026-01-21T12:39:44"
