apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.179
appVersion: ba998fac5b585107a2567e1561dacb185dc9398f
annotations:
  release-date: "2025-11-10T07:44:07"
