apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.307
appVersion: faa6bad8e3f71b3ce90c37c6f9c9ea5f23a842f2
annotations:
  release-date: "2026-02-12T11:20:55"
