apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.195
appVersion: c65e885ff99560da1a0464e394628c698963c91c
annotations:
  release-date: "2025-11-24T10:35:59"
