apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.331
appVersion: 3d586c5220e2d47108ad7e57c3cc4558d6c2ba1b
annotations:
  release-date: "2026-02-27T08:17:59"
