apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.244
appVersion: 6bcde1918904fdb2c528f8d76d8e12487df830a2
annotations:
  release-date: "2025-12-22T15:15:55"
