apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.187
appVersion: 11f4fb06cd7927aa96ac2844f0a6a655f2153f48
annotations:
  release-date: "2025-11-13T10:43:14"
