apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.247
appVersion: f5b68f11f8ebe140e37b7a49f6efaca3f5eafe37
annotations:
  release-date: "2025-12-30T09:39:25"
