apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.290
appVersion: 5ffef91f78e38c5d49c33648941d212a8ba676d3
annotations:
  release-date: "2026-01-30T09:22:57"
