apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.175
appVersion: e3f24f080e4cb26e33fdae945e710e36b1270919
annotations:
  release-date: "2025-11-07T11:33:55"
