apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.185
appVersion: dfc9819e65a2bb23e90b959fadbc348fa50c5e8a
annotations:
  release-date: "2025-11-12T09:53:41"
