apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.200
appVersion: b8cb2d84a54987a2d7269c8d7879be1537b30246
annotations:
  release-date: "2025-11-25T10:10:37"
