apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.325
appVersion: 3103a563a3c6c541df721198563462051fa68f77
annotations:
  release-date: "2026-02-24T16:48:23"
