apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.194
appVersion: ce58c32ebd21247a25407b2e18a0985ede3d6f96
annotations:
  release-date: "2025-11-24T08:04:14"
