apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.288
appVersion: a001853548598a04fcf43b226e537fb1d84d1323
annotations:
  release-date: "2026-01-29T14:16:53"
