apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.313
appVersion: 4527de74978070b4d97ff0972f1b94e6fd863a51
annotations:
  release-date: "2026-02-16T12:56:55"
