apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.292
appVersion: 527baf3e012d547c58fd81a982eff6219449b62b
annotations:
  release-date: "2026-01-30T12:37:04"
