apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.184
appVersion: 505a5c4493ea08a2d1723371693146a357b20dd3
annotations:
  release-date: "2025-11-12T09:41:23"
