apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.189
appVersion: b349e64e5326efdc52df1360e43e202750611b1f
annotations:
  release-date: "2025-11-17T11:19:47"
