apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.327
appVersion: 306a59b1e5d36cae433c2c5383361a2afc09afd0
annotations:
  release-date: "2026-02-26T13:21:34"
