apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.324
appVersion: cb9896fd071167419baabc79d06e82f5d04613c3
annotations:
  release-date: "2026-02-24T07:42:19"
