apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.162
appVersion: 65183366d6f03028749da9f5403cfb760d1ac0c7
annotations:
  release-date: "2025-11-03T12:37:35"
