apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.255
appVersion: c5d4d0f2bc4ec231d7aab8c82964c59dac213fed
annotations:
  release-date: "2026-01-08T12:26:27"
