apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.250
appVersion: 2a22ce56e479e15e82ecd23692463b7ad7952612
annotations:
  release-date: "2026-01-05T12:53:31"
