apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.207
appVersion: 572e293fccfa9ac357cae8f9d3d05c6fcd86df45
annotations:
  release-date: "2025-11-26T13:41:01"
