apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.190
appVersion: 328d1083a318cef7c95957cd7c995858a025833e
annotations:
  release-date: "2025-11-17T11:41:57"
