apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.285
appVersion: b9f46a1f2b8d75d56a5b55ad2ec77c57f16450a6
annotations:
  release-date: "2026-01-28T08:34:14"
