apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.172
appVersion: fe9d76d5a8f4dbf251ed64f6edd22b254c7183a8
annotations:
  release-date: "2025-11-06T12:16:11"
