apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.170
appVersion: a6f8372f3b21da9abd4b1e3a8098658eac3ee15f
annotations:
  release-date: "2025-11-05T15:44:50"
