apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.215
appVersion: 3802555ac9a2b330c8ffd6cfebc24c7ed428052d
annotations:
  release-date: "2025-12-04T12:05:17"
