apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.216
appVersion: e779a16264a9e458b53d434c0fa3cad264a9f3b2
annotations:
  release-date: "2025-12-05T08:42:07"
