apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.227
appVersion: 3e0f66f2b92cc9bf876e1b7a1fcea513eedd5360
annotations:
  release-date: "2025-12-12T07:53:22"
