apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.181
appVersion: 398b8f61b1616eb69fc95266de19ac83e29f580b
annotations:
  release-date: "2025-11-10T10:38:24"
