apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.271
appVersion: 16f42fb9c155226226481ec9ba08b4d99779735a
annotations:
  release-date: "2026-01-20T14:47:23"
