apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.240
appVersion: 79dd3fedadeef6afc0f3514414953ec65a0514ca
annotations:
  release-date: "2025-12-19T10:23:23"
