apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.202
appVersion: 470ccb8426c42e414ae0ddc3d08312b9c6fa319d
annotations:
  release-date: "2025-11-25T12:34:22"
