apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.268
appVersion: 79f04e1dc3a6c8799e3b2e8821e574b1029913e7
annotations:
  release-date: "2026-01-19T11:06:44"
