apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.326
appVersion: 4f79fe72196c34e68ac3ce715e838e82bac46fec
annotations:
  release-date: "2026-02-26T11:44:52"
