apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.264
appVersion: bf4717882f22d1b37dfb7249d08ff278f508c023
annotations:
  release-date: "2026-01-13T11:51:56"
