apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.265
appVersion: c08d381b4de8a870b1625b8ec647c1c805c80ebb
annotations:
  release-date: "2026-01-13T15:42:42"
