apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.289
appVersion: 47855530f49ad0d2a5348a20f94b78b78778f4de
annotations:
  release-date: "2026-01-29T14:31:50"
