apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.309
appVersion: 7d1d8eb09fc397d03cccb86f00fc8a64db8e7e35
annotations:
  release-date: "2026-02-12T13:31:34"
