apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.241
appVersion: 817e39c8a4e43dc058d70c1902f4939aa5182d64
annotations:
  release-date: "2025-12-19T11:45:11"
