apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.210
appVersion: c26cc51f5ee58f8300b8bdeac004ba3d3f48f5c1
annotations:
  release-date: "2025-11-28T14:09:00"
