apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.320
appVersion: 9d6082d49a7b6cb89e03f81f141dfb37562161dc
annotations:
  release-date: "2026-02-18T20:48:03"
