apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.226
appVersion: d75bfa3abc797d7ccaed8f02c2d65906d0875c4e
annotations:
  release-date: "2025-12-11T14:46:06"
