apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.238
appVersion: a01c8a0c03e710ea1c6e89a829f8693aeeb15267
annotations:
  release-date: "2025-12-19T08:02:11"
