apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.225
appVersion: dffc59f93fcb55ab53df0ec4a52c0eed52a7c5e3
annotations:
  release-date: "2025-12-11T12:59:59"
