apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.213
appVersion: 34be001997b0f8fcbc48595d16dcac0d9981421c
annotations:
  release-date: "2025-12-04T10:42:04"
