apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.174
appVersion: ce3eba5f1ff5295d2b11dbda7834ab85519952bf
annotations:
  release-date: "2025-11-07T11:31:29"
