apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.214
appVersion: 64eddc76b31eafc5e24cf3d57887da21cbccb23a
annotations:
  release-date: "2025-12-04T11:32:10"
