apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.246
appVersion: d1dbe70ee17719afa2fd5bc0b182513e9b007a32
annotations:
  release-date: "2025-12-30T09:08:07"
