apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.160
appVersion: bddeebdf269fc1d6c25465d7c5c29241aa5fb775
annotations:
  release-date: "2025-11-03T10:45:17"
