apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.220
appVersion: 4cb0182f0a5ab3a6801abe365e51930ca5673174
annotations:
  release-date: "2025-12-08T12:33:04"
