apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.203
appVersion: e72e12b3d3b6e9e681a181ac85c324fc18fc393e
annotations:
  release-date: "2025-11-25T13:07:33"
