apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.300
appVersion: e091e4a66ce88cdb7a2574dbbbf8ae36f48448ed
annotations:
  release-date: "2026-02-09T14:07:52"
