apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.259
appVersion: c84efc83e58bcc3852959fc0cd34126f579e5b57
annotations:
  release-date: "2026-01-12T10:08:50"
