apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.243
appVersion: d7125a3c897975955495f347c051564112f07c2d
annotations:
  release-date: "2025-12-22T10:54:22"
