apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.217
appVersion: 42ee293a3c3554b05a47d034899b8b82277c160e
annotations:
  release-date: "2025-12-05T10:24:42"
