apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.229
appVersion: 4b3f13712c70ab4ffdc5a9e6c5329a26a1e43e04
annotations:
  release-date: "2025-12-15T14:28:04"
