apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.281
appVersion: 97d535c32d3e8af89b2ba63e8ec1f0f1a144295e
annotations:
  release-date: "2026-01-26T09:32:36"
