apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.234
appVersion: 0daeb4687cfffe1c179e4f5c68ca79fc111eef9d
annotations:
  release-date: "2025-12-17T13:02:33"
