apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.182
appVersion: a19b70747718263844b537261a7b58c39d335223
annotations:
  release-date: "2025-11-10T16:43:36"
