apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.317
appVersion: e42df266f3e98c58250a6c21a8a8bdc75fd26b9e
annotations:
  release-date: "2026-02-18T09:57:54"
