apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.291
appVersion: f6b5a3f8faa3030152f6fd86e7011f7f273535ab
annotations:
  release-date: "2026-01-30T10:37:47"
