apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.205
appVersion: 09afc0ba1425e78768c1fa631249dec9ced28c06
annotations:
  release-date: "2025-11-26T12:01:43"
