apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.168
appVersion: ff85160df6d91b8b406fade6c6a211f60fa5ff9e
annotations:
  release-date: "2025-11-05T10:04:36"
