apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.322
appVersion: 3cc1b36b4e65f28c4b50b4fb54970559b5596a48
annotations:
  release-date: "2026-02-20T10:57:36"
