apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.260
appVersion: f69969f81fba9cd4faa84690152461e1e7d57710
annotations:
  release-date: "2026-01-12T14:18:55"
