apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.263
appVersion: 61f8c5b3a2edbcda63f850bfad6d5ea6b467ca8f
annotations:
  release-date: "2026-01-13T10:21:18"
