apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.330
appVersion: db9bb03d677100c85d0ea88db6cd24b136eae88a
annotations:
  release-date: "2026-02-26T16:01:16"
