apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.193
appVersion: e630a646f95bba6df08992306e1caacd08dcbb1b
annotations:
  release-date: "2025-11-21T13:12:52"
