apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.253
appVersion: b63195be5d71bdd4969ab1a2e405cbc7a2389ccd
annotations:
  release-date: "2026-01-07T15:45:06"
