apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.257
appVersion: 8b9f8251910f688dd18db1d7754056b03a8064cf
annotations:
  release-date: "2026-01-09T08:57:49"
