apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.311
appVersion: 544583d764ed7361f54a515f9d70262eec360b9d
annotations:
  release-date: "2026-02-16T09:41:05"
