apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.221
appVersion: 778dccaf04566f22371e3e0807743f1f3d9e30ea
annotations:
  release-date: "2025-12-09T07:41:50"
