apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.282
appVersion: a4af955a9b915ed9411bc1552210d0943e9df742
annotations:
  release-date: "2026-01-26T11:37:42"
