apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.212
appVersion: 9672ad2ca9398d8bc82768f948d18db5adc18dd8
annotations:
  release-date: "2025-12-03T08:13:42"
