apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.262
appVersion: 23cf5e1c245ec747f8c5af8a67bfd1063d636b10
annotations:
  release-date: "2026-01-13T09:41:35"
