apiVersion: v2
name: castai-watchdog
description: CAST AI Watchdog
type: application
version: 0.2.308
appVersion: e78ca1d23d5b49c2a70b4f30df1fd75967100ffb
annotations:
  release-date: "2026-02-12T11:23:28"
