{{- if .Values.exporter.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "exporter.labels" . | nindent 4 }}
{{- end }}
