{{- if .Values.prometheus.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "exporter.fullname" . }}-prometheus
  labels:
  {{- include "exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "exporter.fullname" . }}-prometheus
subjects:
- kind: ServiceAccount
  name: {{ include "exporter.serviceAccountName" . }}-prometheus
  namespace: {{ .Release.Namespace }}
{{- end }}
