{{- if .Values.prometheus.enabled }}
{{- if .Values.prometheus.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "exporter.serviceAccountName" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "exporter.labels" . | nindent 4 }}
{{- end }}
{{- end }}
