apiVersion: v2
name: castai-spot-handler
description: Spot Handler is the component responsible for scheduled events monitoring and delivering them to the central platform.
type: application
version: 0.18.4
appVersion: "v0.11.1"
