# Default values for castai-hibernate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# CAST AI API URL configuration.
# -- API Url to be used. 
# -- Default: https://api.cast.ai 
# -- (for Europe use https://api.eu.cast.ai)
apiUrl: "https://api.cast.ai"

# CAST AI API Key configuration.
# -- API token with Full Access permissions and encode base64
apiKey: ""

# apiKeySecretRef -- Name of secret with Token to be used for authorizing evictor access to the API
# apiKey and apiKeySecretRef are mutually exclusive
# The referenced secret must provide the token in .data["API_KEY"].
apiKeySecretRef: ""

# -- Set CronJobs "Cloud" env variable to [EKS|GKE|AKS]
cloud: ""

# -- Set CronJobs timezone, if no time zone specified the kube-controller-manager interprets schedules relative to its local time zone
timeZone: ""

# -- hibernate-pause cronjob schedule.
pauseCronJobName: hibernate-pause
# -- update hibernate-pause schedule according to business needs.
pauseCronSchedule: "0 22 * * 1-5"

# -- hibernate-resume cronjob schedule.
resumeCronJobName: hibernate-resume
# -- update hibernate-resume schedule according to business needs.
resumeCronSchedule: "0 7 * * 1-5"

# -- By default namespace is expected to be created by castai-agent.
namespace: castai-agent
agentNamespace: castai-agent

# hibernate cronjob global configurations.
secretName: castai-hibernate

serviceAccountName: hibernate

roleName: hibernate

roleBindingName: hibernate

clusterRoleName: hibernate

clusterRoleBindingName: hibernate

clusterRoleBindingAdminName: hibernate-admin

concurrencyPolicy: "Forbid"

image:
  repository: castai/hibernate
  # -- Tag is set using Chart.yaml appVersion field.
  tag: ""
  pullPolicy: Always

# Override default NAMESPACES_TO_KEEP
# -- Set the NAMESPACES_TO_KEEP environment variable to override, "opa,istio""
namespacesToKeep: ""

# Override default "PROTECT_EVICTION_DISABLED" and set to "true" to prevent the removal of removal-disabled nodes from being removed during hibernate.
# -- This looks for the autoscaling.cast.ai/removal-disabled="true" label on a node and if it exists excludes it from being cordoned and deleted.
protectRemovalDisabled: "false"

configMapName: castai-cluster-controller

restartPolicy: "OnFailure"
backoffLimit: 0

# Pod security context.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext:
  runAsNonRoot: true
  fsGroup: 1003
  runAsGroup: 1003
  runAsUser: 1003

# Override default hibernate-node size
# -- Set the HIBERNATE_NODE environment variable to override the default node sizing selections. Make sure the size selected is appropriate for your cloud.
hibernateNode: ""
